site_name: RevenueHunt Documentation
theme:
  name: material
  features:
    # - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    # - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.indexes # group nav
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    # - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #3D3D64
      accent: #904E95
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #B7CBFF
      accent: #CBDAFF
  analytics:
    gtag: G-31VSB4L8T3
  logo: images/revenuehunt_logo-removebg-preview.png
  favicon: images/revenuehunt-logo-black.webp
nav:
  - Docs:
    - Docs: index.md
    - Tutorials: tutorials/index.md
    - How-to Guides: how-to-guides/index.md
    - App Manual: reference/index.md
    - Customer Success: customer-success/index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Shop Quiz Tour: tutorials/getting-started.md
    - Making your First Quiz: tutorials/making-first-quiz.md
    - Recommending a Skincare Routine: tutorials/skincare-routine.md
    - Using Conditional Logic: tutorials/conditional-logic.md
    - Send follow-up emails with Klaviyo: tutorials/follow-up-emails-klaviyo.md
    - PLAYLIST - One Minute Tutorials: tutorials/playlist-one-minute-tutorials.md
  - How-to Guides:
    - How-to Guides Index: how-to-guides/index.md
    - A/B Test Your Quiz: how-to-guides/ab-test-quiz.md
    - Add Discount: how-to-guides/add-discount.md
    - Add JavaScript: how-to-guides/add-javascript.md
    - Add Product Metafields: how-to-guides/add-product-metafields.md
    - Ask for Marketing Consent: how-to-guides/ask-for-marketing-consent.md
    - Change Checkout Settings: how-to-guides/change-checkout-settings.md
    - Change Quiz Currency: how-to-guides/change-quiz-currency.md
    - Change Quiz Language: how-to-guides/change-quiz-language.md
    - Check Quiz Loading Speed: how-to-guides/check-quiz-loading-speed.md
    - Contact Customer Support: how-to-guides/contact-customer-support.md
    - Copy Quiz from One Store to Another: how-to-guides/copy-the-quiz-from-one-store-to-another.md
    - Create Your First Quiz: how-to-guides/create-first-quiz.md
    - Customize Quiz Design: how-to-guides/customize-quiz-design.md
    - Download Quiz Responses: how-to-guides/download-quiz-responses.md
    - Edit the Results Page: how-to-guides/edit-results-page.md
    - Hide Content with Logic: how-to-guides/hide-content-with-logic.md
    - Hide Out-Of-Stock Products: how-to-guides/hide-out-of-stock-products.md
    - Hide Product Variants: how-to-guides/hide-product-varaints.md
    - Install App: how-to-guides/install-app.md
    - Integrate Facebook Pixel: how-to-guides/integrate-facebook-pixel.md
    - Integrate Google Analytics: how-to-guides/integrate-google-analytics.md
    - Join Questions: how-to-guides/join-questions.md
    - Missing Product Images: how-to-guides/missing-product-images.md
    - Pass Parameters to Pre-Fill Quiz Responses: how-to-guides/pass-parameteres-to-fill-quiz-responses.md
    - Publish the Quiz on Your Website: how-to-guides/publish-quiz.md
    - Recommend Products: how-to-guides/recommend-products.md
    - Recommend Subscription Products: how-to-guides/recommend-subscription-products.md
    - Recommend Slots (Skincare Routine): how-to-guides/recommend-skincare-routine-slots.md
    - Redirect Quiz to Another Page: how-to-guides/redirect-quiz-to-another-page.md
    - Restore Quiz Progress: how-to-guides/restore-quiz-progress.md
    - Send Leads to Your CRM: how-to-guides/send-leads-to-crm.md
    - Send Result Emails: how-to-guides/send-result-emails.md
    - Show Quiz in Shop App: how-to-guides/show-quiz-in-shop-app.md
    - Show Quiz on Customer Profile: how-to-guides/show-quiz-on-customer-profile.md
    - Show Quiz Only to Logged-In Customers: how-to-guides/show-quiz-to-logged-in-customers.md
    - Show Results Explanation: how-to-guides/show-results-explanation.md
    - Sync Catalog: how-to-guides/sync-catalog.md
    - Track Quiz Revenue: how-to-guides/track-quiz-revenue.md
    - Troubleshoot Quiz Results: how-to-guides/troubleshoot-product-results.md
    - Troubleshoot App Issues for WordPress/WooCommerce: how-to-guides/troubleshooting-product-recommendation-quiz-app-issues-for-wordpress-woocommerce.md
    - Use Callback Function: how-to-guides/use-callback-function.md
    - Use Conditional Logic: how-to-guides/use-conditional-logic.md
    - Use Information Recalls: how-to-guides/use-information-recalls.md
    - Use Markdown Language: how-to-guides/use-markdown.md
  - App Manual:
    - App Manual: reference/index.md
    - Dashboard: reference/dashboard.md
    - Quiz Builder: reference/quiz-builder.md
    - Plans & Pricing: reference/plans-pricing.md
    - App Settings: reference/app-settings.md
  - Customer Success:
    - Customer Success: customer-success/index.md
    - Plans & Pricing FAQ: customer-success/plans-pricing-faq.md
    - How to Build a Succesful Shop Quiz: https://revenuehunt.com/how-to-build-a-successful-ecommerce-quiz/
    - How to Reduce Drop Off: customer-success/reduce-dropoff.md
    - Why Products Are Not Added To Cart: customer-success/add-to-cart-issues.md
    - How to Get More People to Take the Quiz: https://revenuehunt.com/11-easy-ways-to-promote-your-quiz-and-get-more-people-to-take-it/
    - How to Build an Effective Sales Funnel with a Product Quiz: https://revenuehunt.com/build-sales-funnel-shopify-store/
    - Product Quiz Metrics What to Track to Convert Better: https://revenuehunt.com/product-quiz-metrics-what-to-track-to-convert-better/
    - How to Use Customer Tags in Product Quizzes to Maximize Sales: https://revenuehunt.com/how-to-use-customer-tags-in-product-quizzes-to-maximize-sales/
    - Smart Ways to Ask for Marketing Consent: https://revenuehunt.com/smart-ways-to-ask-for-marketing-data-processing-consent-in-your-product-recommendation-quiz/
    - How to Create a Video Quiz: https://revenuehunt.com/practical-guide-create-a-video-quiz-for-your-e-commerce-website/
    - Why Your Product Quiz is NOT Converting Well: https://revenuehunt.com/why-your-product-quiz-is-not-converting-well/
    - How to Adapt Product Quizzes for Different Markets and Languages: https://revenuehunt.com/how-to-adapt-product-quizzes-for-different-markets-and-languages/
    - Shopify V2 Beta: customer-success/shopify-v2-beta.md


# plugins:
#   - social

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/RevenueHunt

extra:
  analytics:
    provider: google
    property: G-31VSB4L8T3

extra_javascript:
  - javascripts/feedback.js
  - javascripts/gtag.js
  - javascripts/survey.js


extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.revenuehunt.com/how-to-guides/contact-customer-support/" target="_blank" rel="noopener">feedback form</a>.



extra_css:
  - docs.css

markdown_extensions:
  - toc:
      permalink: true
      title: Table of Contents
      permalink_title: Anchor link to this section for reference
      permalink_class: headerlink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://revenuehunt.com"  target="_blank" rel="noopener">RevenueHunt</a>
