site_name: RevenueHunt Documentation
theme:
  name: material
  features:
    # - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    # - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.indexes # group nav
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    # - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #3D3D64
      accent: #904E95
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #B7CBFF
      accent: #CBDAFF
nav:
  - Docs:
    - Docs: index.md
    - Tutorials: tutorials/index.md
    - How-to Guides: how-to-guides/index.md
    - App Manual: reference/index.md
    - Customer Success: customer-success/index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Getting Started: tutorials/getting-started.md
    - Making your First Quiz: tutorials/making-first-quiz.md
    - Recommending a Skincare Routine: tutorials/skincare-routine.md
    - Conditional Logic: tutorials/conditional-logic.md
    - Send follow-up emails with Klaviyo: tutorials/follow-up-emails-klaviyo.md
    - PLAYLIST - One Minute Tutorials: tutorials/playlist-one-minute-tutorials.md
  - How-to Guides:
    - How-to Guides: how-to-guides/index.md
    - How to Publish the Quiz on Your Website: how-to-guides/how-to-publish-quiz.md
    - How to Copy Quiz from One Store to Another: how-to-guides/how-to-copy-the-quiz-from-one-store-to-another.md
    - How to Add Product Metafields: how-to-guides/how-to-add-product-metafields.md
    - How to Sync Catalog: how-to-guides/how-to-sync-catalog.md
    - How to Add Discount: how-to-guides/how-to-add-discount.md
    - How to Use Information Recalls: how-to-guides/how-to-information-recalls.md
    - How to Send Result Emails from Your Server Using SMTP: how-to-guides/how-to-send-result-emails-from-custom-server.md
    - How to Upgrade Your Plan: how-to-guides/how-to-upgrade-your-plan.md
  - App Manual:
    - App Manual: reference/index.md
    - Dashboard: reference/dashboard.md
    - Quiz Builder: reference/quiz-builder.md
    - Plans & Pricing: reference/plans-pricing.md
    - App Settings: reference/app-settings.md
  - Customer Success:
    - Customer Success: customer-success/index.md
    - How to build a Succesful Product Recommendation Quiz: customer-success/how-to-build-succesful-quiz.md
    - Example 2: customer-success/index.md
    - Example 3: customer-success/index.md

# plugins:
#   - social

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/RevenueHunt

extra_css:
  - docs.css

markdown_extensions:
  - toc:
      permalink: true
      title: Table of Contents
      permalink_title: Anchor link to this section for reference
      permalink_class: headerlink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://revenuehunt.com"  target="_blank" rel="noopener">RevenueHunt</a>
