name: Discord Webhook

on: push

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Webhook
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        TITLE=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
        DESCRIPTION=$(echo "${{ github.event.head_commit.message }}" | tail -n 1)

        curl -X POST -H "Content-Type: application/json" -d '{
          "content": "${{ github.event.head_commit.author.name }}: ${{ github.repository }}/${{ github.ref_name }}",
          "embeds": [{
            "title": "'"$TITLE"'",
            "description": "'"$DESCRIPTION"'",
            "url": "${{ github.event.head_commit.url }}",
            "author": {
              "name": "${{ github.event.head_commit.author.name }}"
            }
          }]
        }' ${{ env.DISCORD_WEBHOOK }} 